### ISSUE TITLE
Problem when trying to pull (doc id 2)

### ISSUE THREAD

**Issue by MoHu3** [bundesverfassung-oesterreich/bv-transkribus-export#35]
Couldnt pull the doc and therefore couldn't push; Info ist: "Kann das entfernte Repository nicht erreichen. Hovern für Details."

**Comment by MoHu3** [comment]
Not sure whether I pushed it or not

**Comment by cfhaak** [comment]
We have to look into that on your local machine. Maybe you forgot to pull upfront?
